### ISSUE TITLE
Missing urllib2

### ISSUE THREAD

**Issue by niklasfyi** [noqqe/rvo#11]
```
Traceback (most recent call last):
  File "/usr/bin/rvo", line 11, in <module>
    load_entry_point('rvo==21.0.0', 'console_scripts', 'rvo')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/rvo/cli.py", line 7, in <module>
    import rvo.utils as utils
  File "/usr/lib/python3.6/site-packages/rvo/utils.py", line 6, in <module>
    import urllib2
ModuleNotFoundError: No module named 'urllib2'
```

I get this error when trying to run rvo in Manjaro Linux.

I also would like to know where to configure the client.

Thanks

**Comment by noqqe** [comment]
Hi @ro0kie4 

sorry I see that you are using python 3, which is not supported at the moment. I added a notice in the readme.

Also now in the readme: Where to define your config :) if is installed normally it tells you that the config in `~/.rvo.conf` was not found if its nonexistent.

**Comment by niklasfyi** [comment]
Great :+1: that explains my Problems. Thanks for the correction
