### ISSUE TITLE
Stats: Tokenizer error, Dependency missing?

### ISSUE THREAD

**Issue by omgwtflaserguns** [noqqe/rvo#7]
```
    salazaar@puffy:/home/salazaar $ rvo list

    ID  Title    Cats    Tags    Date
    ----  -------  ------  ------  ----------
    1  Test                     2016-08-01

    >>> 1 out of 1 result(s).
    salazaar@puffy:/home/salazaar $ rvo stats

    >>> Text analysis

    Traceback (most recent call last):
    File "/usr/local/bin/rvo", line 9, in <module>
    load_entry_point('rvo==21.0.0', 'console_scripts', 'rvo')()
    File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
    File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
    File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
    File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
    File "/usr/local/lib/python2.7/site-packages/rvo/commands/stats.py", line 73, in stats
    table.append(["Sentences" , analysis.get_sentences(content)])
    File "/usr/local/lib/python2.7/site-packages/rvo/analysis.py", line 16, in get_sentences
    sentences = len(nltk.tokenize.sent_tokenize(content))
    File "/usr/local/lib/python2.7/site-packages/nltk/tokenize/__init__.py", line 90, in sent_tokenize
    tokenizer = load('tokenizers/punkt/{0}.pickle'.format(language))
    File "/usr/local/lib/python2.7/site-packages/nltk/data.py", line 801, in load
    opened_resource = _open(resource_url)
    File "/usr/local/lib/python2.7/site-packages/nltk/data.py", line 919, in _open
    return find(path_, path + ['']).open()
    File "/usr/local/lib/python2.7/site-packages/nltk/data.py", line 641, in find
    raise LookupError(resource_not_found)
    LookupError:
    **********************************************************************
    Resource u'tokenizers/punkt/english.pickle' not found.  Please
    use the NLTK Downloader to obtain the resource:  >>>
    nltk.download()
    Searched in:
    - '/home/salazaar/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - u''
    **********************************************************************

```

**Comment by noqqe** [comment]
Yeap. My fault. NLTK has to be initialized after install. Will built _something_

**Comment by noqqe** [comment]
Error gets caught now and presenting the user the options that he has. 
![screenshot 2016-09-02 15 39 59](https://cloud.githubusercontent.com/assets/203902/18205693/9f39614e-7123-11e6-95a2-da0952daa4b8.png)
